### ISSUE TITLE
Decoding of data with lower case letters incompatibility

### ISSUE THREAD

**Issue by hpoul** [Daegalus/dart-base32#10]
Hello,
in version 2.0.0 it was valid to decode base32 codes which contained lower case letters. For example `g33al2j6hqzvdjriwtwp4yhviu744ue4`.
Was this a deliberate choice? It would be nice to be mentioned in the changelog, this is a big incompatibility. I've seen it is now possible to choose the encoding - is there an encoding compatible with how 2.0.0 decoding worked? Is this the only change? 🤔 For now i simply do an `toUpperCase` before decoding. Maybe it's possible to add a note to the `CHANGELOG` in case others stumble upon it.
thanks

**Comment by Daegalus** [comment]
So the base32 spec is case sensitive. Since it's only 32 characters, uppercase vs lowercase are 2 different encodings.

There isn't currently an encoding that supports the same behavior. There are 2 that use lowercase letters, but the order is different, resulting in decoding things incorrectly.

I could add a lowercase encoding that matches the uppercase ones, just know it might not be compatible with other libraries in other languages if that is a requirement.

It's 1am for me, but I will look into giving you a lowercase option and update readmes/changelogs to be more clear about the changes.

My apologies for the inconvenience this has caused.

**Comment by Daegalus** [comment]
I have added a `nonStandardRFC4648Lower` encoding for you to use for lowercase strings in 2.1.2. Hope that helps.
